name: Hello workflow

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Run first job
        run: echo "first job"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Run second job
        run: echo "second job"